name: vibration
description: A plugin for handling Vibration API on iOS, Android, and web.
version: 1.8.4
homepage: https://github.com/benjamindean/flutter_vibration

environment:
  sdk: ">=2.12.1 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  # TODO: Change pub.dev's version when vibration_web is published
  # vibration_web: ^1.6.6
  device_info_plus: ">=9.0.2 <11.0.0"
  flutter_plugin_android_lifecycle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.benjaminabel.vibration
        pluginClass: VibrationPlugin
      ios:
        pluginClass: VibrationPlugin
      # web:
      #   default_package: vibration_web
